#!/bin/python

with open("example.cimg", "wb") as file:
    file.write(b"cIMG") 
    file.write((2).to_bytes(4, "little"))
    
    file.write((73).to_bytes(8, "little")) 
    file.write((20).to_bytes(2, "little")) 
    
    asu_maroon_r = 0x8C
    asu_maroon_g = 0x1D
    asu_maroon_b = 0x40
    
    for _ in range(73 * 20):
        file.write(bytes([asu_maroon_r, asu_maroon_g, asu_maroon_b, ord('X')]))
